//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000.
        /// </summary>
        public static string Defauld_Guid {
            get {
                return ResourceManager.GetString("Defauld_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} &lt;{1}&gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string Error_Msg_Duplicate {
            get {
                return ResourceManager.GetString("Error_Msg_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chuyển đổi không được trùng nhau..
        /// </summary>
        public static string Error_Msg_Dupplicate_Conversion {
            get {
                return ResourceManager.GetString("Error_Msg_Dupplicate_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chuyển đổi không được trùng với đơn vị tính chính..
        /// </summary>
        public static string Error_Msg_Dupplicate_Unit {
            get {
                return ResourceManager.GetString("Error_Msg_Dupplicate_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được để trống..
        /// </summary>
        public static string Error_Msg_Empty {
            get {
                return ResourceManager.GetString("Error_Msg_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không đúng định dạng..
        /// </summary>
        public static string Error_Msg_Invalid {
            get {
                return ResourceManager.GetString("Error_Msg_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được dài quá {1} ký tự..
        /// </summary>
        public static string Error_Msg_Length {
            get {
                return ResourceManager.GetString("Error_Msg_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu được chấp nhận nhưng việc xử lý chưa hoàn thành..
        /// </summary>
        public static string ExceptionAcceptedMsgError {
            get {
                return ResourceManager.GetString("ExceptionAcceptedMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ..
        /// </summary>
        public static string ExceptionDevMsgError {
            get {
                return ResourceManager.GetString("ExceptionDevMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có nội dung trả về cho yêu cầu này..
        /// </summary>
        public static string ExceptionNoContentMsgError {
            get {
                return ResourceManager.GetString("ExceptionNoContentMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string ExceptionUserMsgError {
            get {
                return ResourceManager.GetString("ExceptionUserMsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Delete{0}.
        /// </summary>
        public static string Proc_Delete {
            get {
                return ResourceManager.GetString("Proc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_GetSingle{0}.
        /// </summary>
        public static string Proc_GetSingle {
            get {
                return ResourceManager.GetString("Proc_GetSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Insert{0}.
        /// </summary>
        public static string Proc_Insert {
            get {
                return ResourceManager.GetString("Proc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_Update{0}.
        /// </summary>
        public static string Proc_Update {
            get {
                return ResourceManager.GetString("Proc_Update", resourceCulture);
            }
        }
    }
}
